version: "3.9"

services:
  analytics:
    build: .
    container_name: analytics_service
    environment:
      MIX_ENV: prod

      # Phoenix
      HOST: analytic.labsflow.ru
      PORT: 4000
      SECRET_KEY_BASE: "your-secret-here"

      # ClickHouse

    ports:
      - "4001:4000"
    # depends_on:
    #   - clickhouse
    restart: always
