version: "3.9"

services:
  analytics:
    build: .
    container_name: analytics_service
    environment:
      MIX_ENV: prod

      # Phoenix
      HOST: analytic.labsflow.ru
      PORT: 4000
      SECRET_KEY_BASE: "your-secret-here"

      # ClickHouse
      CLICKHOUSE_HOST: 178.154.220.66
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "unicode"
      CLICKHOUSE_DB: welder_production
      CLICKHOUSE_POOL: 2
    ports:
      - "4001:4000"
    # depends_on:
    #   - clickhouse
    restart: always
